name             'git-deploy'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures git-deploy'
long_description 'Installs/Configures git-deploy'
version          '0.1.1'
